import CAMPAIGN_ABI from "./abi/Campaign.json";
import CAMPAIGN_FACTORY_ABI from "./abi/CampaignFactory.json";

const DEFAULT_CAMPAIGN_ADDRESS = "0x18964273CA201F71Ac2a3Aa8eE807B652419E345";
const CAMPAIGN_FACTORY_ADDRESS = "0x06412b42ca7eafb1f3b2cd7fcd69f8337efc2725";

const EVENT_POLLING_INTERVAL = 2000; // In miliseconds
const CAMPAIGN_FACTORY_BLOCK_NUMBER = 7257911; // The block number of the block in which the CampaignFactory contract is deployed

const MAX_NUM_DONORS = 50;

export {
  CAMPAIGN_ABI,
  CAMPAIGN_FACTORY_ABI,
  CAMPAIGN_FACTORY_ADDRESS,
  CAMPAIGN_FACTORY_BLOCK_NUMBER,
  DEFAULT_CAMPAIGN_ADDRESS,
  EVENT_POLLING_INTERVAL,
  MAX_NUM_DONORS,
};
