import CAMPAIGN_ABI from "./Campaign.json";
import CAMPAIGN_FACTORY_ABI from "./CampaignFactory.json";
const CAMPAIGN_FACTORY_ADDRESS = "0x4fCE0bc594a701E8D57B607AfeaAa1c8b660436e";

export { CAMPAIGN_ABI, CAMPAIGN_FACTORY_ABI, CAMPAIGN_FACTORY_ADDRESS };
