import CAMPAIGN_ABI from "./Campaign.json";
import CAMPAIGN_FACTORY_ABI from "./CampaignFactory.json";
const CAMPAIGN_FACTORY_ADDRESS = "0x9C7A041da26153aE8acd5A419273c4aC37C12Ad3";

export { CAMPAIGN_ABI, CAMPAIGN_FACTORY_ABI, CAMPAIGN_FACTORY_ADDRESS };

